name: Setup
description: Set up environment and install dependencies

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 14.x

    - run: yarn --frozen-lockfile
      shell: bash
