name: Setup
description: Set up environment and install dependencies

runs:
  using: composite
  steps:
    - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
      with:
        node-version-file: .nvmrc

    - run: yarn --frozen-lockfile
      shell: bash
