name: Setup
description: Set up environment and install dependencies

runs:
  using: composite
  steps:
    - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
      with:
        node-version-file: .nvmrc

    - run: yarn --frozen-lockfile
      shell: bash
