name: Setup
description: Set up environment and install dependencies

runs:
  using: composite
  steps:
    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version-file: .nvmrc

    - run: yarn --frozen-lockfile
      shell: bash
