name: Setup
description: Set up environment and install dependencies

runs:
  using: composite
  steps:
    - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6
      with:
        node-version-file: .nvmrc

    - run: yarn --frozen-lockfile
      shell: bash
