# Something is wrong with changesets action npm auth, plus the PR isn't actually that helpful...
# Just go with manual releases using `yarn changeset version`, commit, npm publish instead.

name: Release

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    environment: release

    steps:
      - uses: actions/checkout@v3
        with:
          # fetch all history
          fetch-depth: 0
          # don't save creds in the git config (so it's easier to override later)
          persist-credentials: false

      - name: Setup
        uses: ./.github/actions/setup

      - run: yarn build

      - run: yarn test

      - name: Create release PR or publish to npm
        uses: changesets/action@v1
        with:
          publish: yarn release
          commit: Bump package version
          title: Bump package version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
