name: Setup, build, test
description: Set up environment, build, and test

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 14.x

    - run: yarn --frozen-lockfile

    - run: yarn format:check

    - run: yarn build

    - run: yarn test
