name: Setup, build, test
description: Set up environment, build, and test

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 14.x

    - run: yarn --frozen-lockfile
      shell: bash

    - run: yarn format:check
      shell: bash

    - run: yarn build
      shell: bash

    - run: yarn test
      shell: bash
