name: Release

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup, build, test
        uses: ./.github/actions/setup-build-test

      - name: Create release PR or publish to npm
        uses: changesets/action@v1
        with:
          publish: yarn release
          commit: Bump package version
          title: Bump package version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
